@extends('layouts.admin')
@section('title','Site Settings')
@section('content')
<div class="p-6 max-w-6xl"><h1 class="text-2xl font-bold">Site settings</h1><p class="text-slate-500">Control branding, homepage, contact details, global SEO, and footer content.</p>@if(session('success'))<div class="alert alert--success mt-5">{{ session('success') }}</div>@endif<form method="POST" action="{{ route('admin.settings.site.update') }}" class="mt-6 space-y-6">@csrf @method('PUT')
@php $groups=[
'Brand & homepage'=>[['site_name','Site name','text'],['site_tagline','Tagline','text'],['site_logo','Logo URL','url'],['site_logo_dark','Dark logo URL','url']],
'Contact details'=>[['contact_email','Email','email'],['contact_phone','Phone','text'],['contact_address','Address','textarea'],['social_facebook','Facebook URL','url'],['social_linkedin','LinkedIn URL','url'],['social_youtube','YouTube URL','url']],
'Footer'=>[['footer_text','Footer description','textarea'],['copyright_text','Copyright text','text']],
'Blog index'=>[['blog_title','Blog heading','text'],['blog_description','Blog introduction','textarea'],['blog_per_page','Posts per page','number']],
'Global SEO defaults'=>[['default_meta_title','Default meta title','text'],['default_meta_description','Default meta description','textarea'],['default_social_image','Default social image URL','url']],
]; @endphp
<section class="card"><div class="card__header"><h2 class="card__title">Homepage</h2></div><div class="card__body"><label class="form__label">Published page used as homepage</label><select name="homepage_id" class="form__select"><option value="">Built-in fallback homepage</option>@foreach($pages as $page)<option value="{{ $page->id }}" @selected(($settings['homepage_id']??null)==$page->id)>{{ $page->title }}{{ $page->is_published?'':' (draft)' }}</option>@endforeach</select></div></section>
@foreach($groups as $heading=>$fields)<section class="card"><div class="card__header"><h2 class="card__title">{{ $heading }}</h2></div><div class="card__body grid md:grid-cols-2 gap-5">@foreach($fields as [$name,$label,$type])<label class="form__group {{ $type==='textarea'?'md:col-span-2':'' }}"><span class="form__label">{{ $label }}</span>@if($type==='textarea')<textarea name="{{ $name }}" class="form__textarea" maxlength="{{ $name==='default_meta_description'?160:1000 }}">{{ old($name,$settings[$name]??'') }}</textarea>@else<input type="{{ $type }}" name="{{ $name }}" class="form__input" value="{{ old($name,$settings[$name]??'') }}">@endif</label>@endforeach</div></section>@endforeach
<section class="card"><div class="card__header"><h2 class="card__title">Lead notifications</h2></div><div class="card__body space-y-4"><label class="flex items-center gap-3"><input type="checkbox" name="notifications_email_enabled" value="1" @checked(old('notifications_email_enabled',$settings['notifications_email_enabled']??true))><span>Send admin email alerts for new leads</span></label><label class="flex items-center gap-3"><input type="checkbox" name="notifications_whatsapp_enabled" value="1" @checked(old('notifications_whatsapp_enabled',$settings['notifications_whatsapp_enabled']??false))><span>Send official WhatsApp Business template alerts</span></label><p class="text-sm text-slate-500">Provider credentials and recipient addresses remain environment or secrets-manager settings. WhatsApp alerts contain no PHI or full lead message.</p><a href="{{ route('admin.notifications.index') }}" class="text-blue-600">Review notification deliveries</a></div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Privacy-first analytics</h2></div><div class="card__body grid md:grid-cols-2 gap-5"><label class="flex items-center gap-3"><input type="checkbox" name="analytics_enabled" value="1" @checked(old('analytics_enabled',$settings['analytics_enabled']??true))><span>Count anonymous public page visits</span></label><label><span class="form__label">Raw event retention (days)</span><input class="form__input" type="number" min="30" max="730" name="analytics_retention_days" value="{{ old('analytics_retention_days',$settings['analytics_retention_days']??180) }}"></label><p class="md:col-span-2 text-sm text-slate-500">No raw IP, full referrer URL, user account, or persistent cookie is stored. Do Not Track is respected.</p></div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Custom CSS</h2></div><div class="card__body"><p class="text-sm text-slate-500 mb-3">Advanced administrators only. CSS is applied after the theme stylesheet.</p><textarea name="custom_css" class="form__textarea font-mono" rows="12">{{ old('custom_css',$settings['custom_css']??'') }}</textarea></div></section><div class="flex justify-end"><button class="btn btn--primary">Save site settings</button></div></form></div>
@endsection
