@extends('layouts.admin')
@section('title','Visitor Analytics')
@section('content')
<div class="p-6"><div class="flex flex-col md:flex-row md:items-end justify-between gap-4"><div><h1 class="text-2xl font-bold">Visitor analytics</h1><p class="text-slate-500">Privacy-first, cookieless page views. Raw IP addresses and user agents are never stored.</p></div><form class="flex flex-wrap gap-2"><label class="text-xs">From<input class="form__input" type="date" name="start" value="{{ $start->toDateString() }}"></label><label class="text-xs">To<input class="form__input" type="date" name="end" value="{{ $end->toDateString() }}"></label><button class="btn btn--primary self-end">Apply</button><a class="btn btn--secondary self-end" href="{{ route('admin.analytics.export',['start'=>$start->toDateString(),'end'=>$end->toDateString()]) }}">Export CSV</a></form></div>
<div class="grid sm:grid-cols-2 lg:grid-cols-4 gap-4 mt-6"><div class="card p-5"><span class="text-sm text-slate-500">Page views</span><strong class="block text-3xl mt-1">{{ number_format($totalViews) }}</strong></div><div class="card p-5"><span class="text-sm text-slate-500">Unique visitor-days</span><strong class="block text-3xl mt-1">{{ number_format($uniqueVisitors) }}</strong></div><div class="card p-5"><span class="text-sm text-slate-500">Views per visitor</span><strong class="block text-3xl mt-1">{{ $uniqueVisitors?number_format($totalViews/$uniqueVisitors,1):'0' }}</strong></div><div class="card p-5"><span class="text-sm text-slate-500">Reporting period</span><strong class="block text-xl mt-2">{{ $start->format('M j') }} – {{ $end->format('M j, Y') }}</strong></div></div>
<div class="grid xl:grid-cols-2 gap-6 mt-6"><section class="card"><div class="card__header"><h2 class="card__title">Traffic trend</h2></div><div class="card__body space-y-2">@php $max=max(1,(int)$daily->max('views')); @endphp @forelse($daily as $row)<div class="grid grid-cols-[90px_1fr_70px] gap-3 items-center text-sm"><span>{{ \Carbon\Carbon::parse($row->visited_on)->format('M j') }}</span><div class="h-5 bg-slate-100 rounded"><div class="h-5 bg-blue-600 rounded" style="width:{{ max(2,($row->views/$max)*100) }}%"></div></div><span class="text-right">{{ $row->views }}</span></div>@empty<p>No visits in this period.</p>@endforelse</div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Device breakdown</h2></div><div class="card__body">@forelse($devices as $row)<div class="flex justify-between border-b py-3"><span>{{ str($row->device_type)->headline() }}</span><strong>{{ number_format($row->views) }}</strong></div>@empty<p>No device data.</p>@endforelse</div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Top pages</h2></div><div class="overflow-x-auto"><table><thead><tr><th>Path</th><th>Views</th><th>Visitors</th></tr></thead><tbody>@foreach($topPages as $row)<tr><td class="max-w-md truncate" title="{{ $row->path }}">{{ $row->path }}</td><td>{{ $row->views }}</td><td>{{ $row->visitors }}</td></tr>@endforeach</tbody></table></div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Referrer domains</h2></div><div class="card__body">@forelse($sources as $row)<div class="flex justify-between border-b py-3"><span class="truncate">{{ $row->referrer_host }}</span><strong>{{ $row->views }}</strong></div>@empty<p>Traffic is direct or no referrer was supplied.</p>@endforelse</div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Countries</h2></div><div class="card__body">@forelse($countries as $row)<div class="flex justify-between border-b py-3"><span>{{ $row->country_code }}</span><span><strong>{{ $row->views }}</strong> views · {{ $row->visitors }} visitors</span></div>@empty<p>Country data is unavailable. Enable trusted Geo headers at your proxy or CDN.</p>@endforelse</div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Cities and regions</h2></div><div class="card__body">@forelse($cities as $row)<div class="flex justify-between border-b py-3"><span>{{ $row->city }}{{ $row->region?', '.$row->region:'' }} {{ $row->country_code }}</span><strong>{{ $row->views }}</strong></div>@empty<p>No city-level data is available.</p>@endforelse</div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Browsers</h2></div><div class="card__body">@foreach($browsers as $row)<div class="flex justify-between border-b py-3"><span>{{ $row->browser }}</span><strong>{{ $row->views }}</strong></div>@endforeach</div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Operating systems</h2></div><div class="card__body">@foreach($operatingSystems as $row)<div class="flex justify-between border-b py-3"><span>{{ $row->operating_system }}</span><strong>{{ $row->views }}</strong></div>@endforeach</div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Reach method</h2></div><div class="card__body">@foreach($reachTypes as $row)<div class="flex justify-between border-b py-3"><span>{{ str($row->reach_type)->headline() }}</span><strong>{{ $row->views }}</strong></div>@endforeach</div></section>
<section class="card"><div class="card__header"><h2 class="card__title">Network organizations</h2></div><div class="card__body">@forelse($organizations as $row)<div class="flex justify-between border-b py-3"><span class="truncate">{{ $row->organization }}</span><strong>{{ $row->views }}</strong></div>@empty<p>Organization data is unavailable.</p>@endforelse</div></section>
<section class="card xl:col-span-2"><div class="card__header"><h2 class="card__title">Campaign traffic</h2></div><div class="overflow-x-auto"><table><thead><tr><th>Source</th><th>Medium</th><th>Campaign</th><th>Views</th></tr></thead><tbody>@forelse($campaigns as $row)<tr><td>{{ $row->utm_source }}</td><td>{{ $row->utm_medium?:'—' }}</td><td>{{ $row->utm_campaign?:'—' }}</td><td>{{ $row->views }}</td></tr>@empty<tr><td colspan="4">No UTM campaign traffic.</td></tr>@endforelse</tbody></table></div></section></div>
<section class="card mt-6"><div class="card__header"><h2 class="card__title">Recent anonymous visits</h2></div><div class="overflow-x-auto"><table><thead><tr><th>Time</th><th>Page</th><th>Location</th><th>Device</th><th>Browser / OS</th><th>Reach</th><th>Referrer / organization</th></tr></thead><tbody>@forelse($recentVisits as $visit)<tr><td class="whitespace-nowrap">{{ $visit->created_at->format('M j H:i') }}</td><td class="max-w-xs truncate">{{ $visit->path }}</td><td>{{ $visit->city?:$visit->region?:$visit->country_code?:'Unknown' }}</td><td>{{ str($visit->device_type)->headline() }}</td><td>{{ $visit->browser }} / {{ $visit->operating_system }}</td><td>{{ str($visit->reach_type)->headline() }}</td><td>{{ $visit->referrer_host?:$visit->organization?:'Direct' }}</td></tr>@empty<tr><td colspan="7">No visits recorded.</td></tr>@endforelse</tbody></table></div></section>
<p class="mt-6 text-xs text-slate-500">Unique visitors are estimated with a one-way, daily rotating hash and cannot be used to identify a person across days. Requests with Do Not Track are excluded.</p></div>
@endsection
