@extends('layouts.admin')
@section('title','Pages')
@section('content')
<div class="p-6"><div class="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 class="text-2xl font-bold">Pages</h1><p class="text-slate-500">Build, review, publish, and recover site pages.</p></div><a href="{{ route('admin.pages.create') }}" class="btn btn--primary">Create page</a></div>
@if(session('success'))<div class="alert alert--success my-5">{{ session('success') }}</div>@endif
<nav class="my-6 flex flex-wrap gap-2" aria-label="Page status filters">@foreach([''=>'All','published'=>'Published','draft'=>'Drafts','trash'=>'Trash'] as $value=>$label)<a class="rounded px-4 py-2 {{ request('status','')===$value?'bg-slate-900 text-white':'bg-white' }}" href="{{ route('admin.pages.index',array_filter(['status'=>$value])) }}">{{ $label }}</a>@endforeach</nav>
<div class="bg-white rounded-xl shadow overflow-x-auto"><table class="w-full"><thead class="bg-slate-50"><tr><th class="text-left p-4">Page</th><th class="text-left p-4">Status</th><th class="text-left p-4">Views</th><th class="text-left p-4">Updated</th><th class="text-right p-4">Actions</th></tr></thead><tbody>
@forelse($pages as $page)<tr class="border-t"><td class="p-4"><strong>{{ $page->title }}</strong><div class="text-sm text-slate-500">/{{ $page->slug }}</div></td><td class="p-4"><span class="badge {{ $page->trashed()?'badge--danger':($page->is_published?'badge--success':'badge--warning') }}">{{ $page->trashed()?'Trashed':($page->is_published?'Published':'Draft') }}</span></td><td class="p-4 text-sm font-semibold">{{ number_format($page->visits_count) }}</td><td class="p-4 text-sm text-slate-500">{{ $page->updated_at->diffForHumans() }}</td><td class="p-4"><div class="flex justify-end gap-3">@if($page->trashed())<form method="POST" action="{{ route('admin.pages.restore',$page->id) }}">@csrf<button class="text-blue-600">Restore</button></form><form method="POST" action="{{ route('admin.pages.force-delete',$page->id) }}" onsubmit="return confirm('Permanently delete this page and its revisions?')">@csrf @method('DELETE')<button class="text-red-600">Delete forever</button></form>@else<a class="text-blue-600" href="{{ route('admin.pages.builder.edit',$page) }}">Build</a><a class="text-slate-600" href="{{ route('admin.pages.revisions',$page) }}">Revisions</a><a class="text-slate-600" href="{{ route('admin.pages.edit',$page) }}">Settings</a>@if($page->is_published)<a target="_blank" rel="noopener" href="{{ route('page.show',$page->slug) }}">View</a>@endif<form method="POST" action="{{ route('admin.pages.destroy',$page) }}" onsubmit="return confirm('Move this page to trash?')">@csrf @method('DELETE')<button class="text-red-600">Trash</button></form>@endif</div></td></tr>
@empty<tr><td colspan="5" class="p-10 text-center text-slate-500">No pages found.</td></tr>@endforelse
</tbody></table></div><div class="mt-6">{{ $pages->links() }}</div></div>
@endsection
